### ISSUE TITLE
Architecture design

### ISSUE THREAD

**Issue by chaoran-chen** [MusicConnectionMachine/VisualizationG5#21]
Hey. As the follow-up to https://github.com/MusicConnectionMachine/VisualizationG5/pull/19#discussion_r104558249, I think we should speak a bit about our architecture again, and this time come to a decision.

I believe that it would be nice to have 3 components at the end.
* An REST-JSON-API-Server that delivers data and can maybe be opened up to be used for other developers.
* A set of React components (Person-Relationships-Graph, Timeline, (maybe) search bar etc.) that can be distributed. They can be included in every site just by including a .js and .css file or maybe also as React plugin.
* (least important) A full-fledged site with an own navigation and so on that uses the React components.

If we want to use this approach, the components must render their stuff by themselves. The Express server is only allowed to render things like the navigation and header, but nothing that is relevant to the components. What do you think?

**Comment by martomi** [comment]
I fully agree with you 👍  Also as a follow-up on the discussion from #19, our components should not expect data to be pre-loaded from the express server. Example is the `SearhResultsComponent` which currently renders the view by directly accessing data from `window.__dataForReact`. In order to have reusable and embeddable components we should use props instead. This would allow us to add a case-specific wrapper component that will manage the data (e.g. fetch it from API in case of a widget or access the pre-loaded data from express in case it's on the website) and feed it into the child component. That would make the component truly reusable!

**Comment by lustoykov** [comment]
Spot on. I'm closing the issue, we seem to agree.
