### ISSUE TITLE
Grouping of Relationships for Graphical Representation

### ISSUE THREAD

**Issue by martomi** [MusicConnectionMachine/VisualizationG5#24]
For our relationship graph we want to be able to group the entities with their relations in a meaningful way. This would allow us to reduce the total number of nodes and maintain an easily browsable graph. Optimally, we would have our entity of interest in the center of the graph and all relations would be representable as links to a small (maybe <10 ?) number of groups around it. The user should be able to click on any of those groups to expand them and see the entities inside. Related to the Person graph: #16 

What possibilities for grouping/clustering of relationships do we have?
Maybe someone from @MusicConnectionMachine/group-3 @MusicConnectionMachine/group-4 could give us some thoughts? Thanks!

**Comment by simonzachau** [comment]
Regarding the rough number 10 it sounds valid (compared to the [relationships](https://github.com/MusicConnectionMachine/RelationshipsG4/blob/develop/documents/Relationships.txt) we are hoping to be able to extract in the future).

For now we are still trying to find a way to mine the data. Of course it's nice to know any special requirements we should be careful about.

**Comment by gyachdav** [comment]
@vviro what would be an interesting and intuitive secondary dimension to group composers. Things that come to my mind are period, style, school etc. your expertise here is needed.

**Comment by gyachdav** [comment]
Paging @vviro

**Comment by vviro** [comment]
I'm not quite sure if there are many different meaningful ways for grouping composers that are accessible to us data-wise. Simple natural groupings could be by time period, geography (e,g, place of birth, which is however not that interesting since people did move around). For musicians that's of course same as above plus their instruments. But this all doesn't seem very exciting. If we get some interesting relations or attributes from the unstructured data and the relations groups, then we could think of using them for grouping, and then probably there would be many aspects under which one could group the composers. In fact, how about planning for this in advance? This of course requires some coordination between the groups, but if the grouping principle could be more like free text (at least with multiple auto-suggest options), this could potentially be quite powerful. So I would actually argue for an open approach instead of fixing the dimensions in advance.

**Comment by chaoran-chen** [comment]
Closed because it's obsolete.
