### ISSUE TITLE
Adjust relationship widget to provided mockups

### ISSUE THREAD

**Issue by lustoykov** [MusicConnectionMachine/VisualizationG5#61]
@martomi starts with the search top bar (styles + provide callback when user types in)
@martomi implements API calls when user types in the search bar and populates data into state

My suggestion is for now to load top 50 relations + entities determined by server algorithm for given entity so that search could be quicker and pagination easier to implement. Search would act as a filter on React’s state in this case.
Later we can implement load on demand with search on server if we feel like the top 50 entities are not enough for the user to explore and there is enough time.

@lustoykov starts with adjusting and styling the table UI + Popups

I will expect data format like this:
```js
{ 
   entities: [ { title: '...' }, ... ],
   relations: [ { title: '...' }, ... ],
}
```

Next we'll implement the details view.

**Comment by lustoykov** [comment]
We're working on the branch https://github.com/MusicConnectionMachine/VisualizationG5/tree/relation-widget

**Comment by lustoykov** [comment]
OK, now the details view is on its way.

**Comment by lustoykov** [comment]
STATUS (provided by @martomi)
----


1. making entities detail view
2. providing a close button for popovers (top right with icon)
3. Sources popover can have a list of source (see mockups) and we want to only show a few of them and make it possible to include a link that would contain all sources on some other page
4. fix full screen mode (you’ve written a TODO it’s not working properly (why not?) I think it’s not working properly in your detailsview, but I haven’t gotten on to refactor the styling there
5. social sharing
6. Highlighting of filtered words (see mockup - unless too complex)
7. API
8. Fixing all bugs
9. Final Polishing / Refactoring / Styling (edited)

We're doing our best to finish it by end of this week. It is a lot of work.

https://github.com/MusicConnectionMachine/VisualizationG5/commits/relation-widget

**Comment by lustoykov** [comment]
### Status UPDATE

1. making entities detail view - **DONE** by @lustoykov
2. providing a close button for popovers (top right with icon) - **DONE** by @lustoykov
3. Sources popover can have a list of source (see mockups) and we want to only show a few of them and make it possible to include a link that would contain all sources on some other page **TODO** by @martomi 
4. fix full screen mode (you’ve written a TODO it’s not working properly (why not?) I think it’s not working properly in your detailsview, but I haven’t gotten on to refactor the styling there **DONE.** by @lustoykov
5. social sharing  **TODO** by @martomi 
6. Highlighting of filtered words (see mockup - unless too complex) **TODO** by @martomi 
7. API **TODO** by @chaoran-chen 
8. Fixing all bugs **TODO AT HACKATHON** by @martomi, @lustoykov
9. Final Polishing / Refactoring / Styling **TODO AT HACKATHON** by @lustoykov, @martomi 

*Bonus: now we persist state between searches (when you go back to all relations, your search query and page number are being restored)* by @lustoykov

*TODO Bonus: Show sources / Popovers in details views* by @martomi


# PR Coming by Sunday after 3, 5 and 6 are done.

**Comment by kordianbruck** [comment]
Thanks for keeping us posted! :+1:

**Comment by kordianbruck** [comment]
I've been hitting refresh / F5 every 5 seconds since Friday - so whats up?

Nevermind - its in the PR - *shame on me*

**Comment by pfent** [comment]
@kordianbruck leaving the trapfall open for others: *ding* **shame** *ding*

**Comment by kordianbruck** [comment]
This is not yet implemented - so we should not close this issue

**Comment by sacdallago** [comment]
# NOW
![](http://ps3media.ign.com/ps3/image/article/102/1026159/tekken-6-screens-20090918093947227.jpg)

**Comment by gyachdav** [comment]
@martomi what are the chances we will implement the Spotify layout during the hackathon? If this is not realistic a than what is your time/effort estimate to convert the widget to the mockup described in #56

**Comment by martomi** [comment]
@gyachdav My plan for tomorrow was rather integrating the widget functionalities with a real and functional API. Currently, all the API calls are mocked on the front end. Endpoints would most likely need to be added / adjusted on the backend. I expect issues would arise during the integration so that there should be enough work for the day in order to hopefully get everything up and running smoothly including doing some testing and fixing all outstanding issues.

Regarding the Spotify-like SPA version of the relation exploration tool: No work has started on that thus far, starting from scratch I think it would take about 2 full days of work to come up with a first prototype and maybe 2 days more for a production ready version. That would include defining new API endpoints since the different representation can't use the same API as the current widget. Implementing said endpoints and implementing the layout including all possibilities for dynamic loading on the entity and relation levels. It would have to be implemented from scratch.I don't see a meaningful way for converting the current widget as the concept of representation differs greatly.

**Comment by lustoykov** [comment]
I'll just post the facts and you decide if 2-3 days are realistic:

- The small widget took about 5 full time work days to get it to this point 
- On top, @chaoran-chen  has implemented an API which currently is not sure if it works, because
there is no data, so let's say when we are finished there, this is 1 day more
- Then we need to integrate them and fix bugs, if any 
- Also, the feedback Popover is only mockup, if we want to save it in the DB it would take
also a day to polish it, come up with models, PR review, merge
- Then we have another big issue with URL parsing to map Widget < -> Composer, about 4 hours
- Then we need to deploy it
- I'll exclude the multiple hours we spent on communication

**In total: at least 8 days for the small widget.**


So in my opinion it is unrealistic to finish it in anything below 4 days and be production ready and **if I had to guess, it would take 8-10 days to implement something we could show the world and be proud of.**

https://twitter.com/rvagg/status/850126885581340672

**Comment by chaoran-chen** [comment]
@lustoykov, you've just summoned a developer who's sitting somewhere in Beijing ;)

PS. reply from @lustoykov not to flood: This was AI from github I think, my initial post wrote "Chaoran" :D

**Comment by gyachdav** [comment]
@vviro is the feedback popover really necessary?

**Comment by vviro** [comment]
@gyachdav hard to tell like that, let's see tomorrow.

**Comment by kordianbruck** [comment]
Can we use the same API? https://github.com/MusicConnectionMachine/api/issues/90

@martomi - if so please open a new issue to link your feedback widget with that api.

**Comment by martomi** [comment]
That API doesn't seem to be universal for all kinds of resources by looking at the POST URI `POST /events/:event_id/feedback` We'd need a similar `/relations/:relation_id/feedback` endpoint.
Otherwise the current implementation could be partially reused with the "wrong_data" type, but we also have an optional comment that won't be saved. We need to have additional parameter for comment.

<img width="404" alt="screen shot 2017-04-23 at 14 17 51" src="https://cloud.githubusercontent.com/assets/3739458/25313511/2af568b8-2830-11e7-8440-489c09d24598.png">

@chaoran-chen Have you worked on the API for relation feedback yet?
