### ISSUE TITLE
Access the API

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/VisualizationG5#64]
We need the widgets to actually fetch the data from the api - as I know this is not yet done right?

**Comment by chaoran-chen** [comment]
This front-end part of this issue is mostly done and also the swagger-api part is generally finished but there are still two blocking issues: 
* https://github.com/MusicConnectionMachine/api/issues/101
* There is still no data so that it is hard to evaluate if the implementations are really correct.

I hope that we (including the back-end groups) can fix them tomorrow during the hackathon but because of those issues, it is not possible to hit the deadline.

**Comment by kordianbruck** [comment]
Will track in individual issues for a better overview.
