### ISSUE TITLE
Still needed APIs

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/VisualizationG5#74]
So we got a ton of features now in this repo but I'm not really sure, where we are missing APIs and which are already done / in progress.

Did everyone create an issue in the API project if they require an endpoint? 

@MusicConnectionMachine/group-5

**Comment by chaoran-chen** [comment]
#### For using inside of IMSLP:
https://github.com/MusicConnectionMachine/api/issues/101
#### For our own SPA:
* Relations: https://github.com/MusicConnectionMachine/api/pull/100. It is maybe already working as it is but we don't know it since there is no data in the database.
* Timeline: https://github.com/MusicConnectionMachine/api/issues/22. Here, the front-end part is not implemented, which is easy to do but then we will still get the same problem like in the point above described.
* Map: Could be completely finished but ... no data.
* Feedback for relationships https://github.com/MusicConnectionMachine/api/issues/122

**Comment by kordianbruck** [comment]
So feedback is done for relationship widget? Already integrated?

**Comment by martomi** [comment]
See also #61 I don't think we have that API yet, @chaoran-chen ?

**Comment by kordianbruck** [comment]
@martomi please an issue in the API then please.

**Comment by chaoran-chen** [comment]
Nothing to do here anymore  - it's all covered by other issues.
